name: CI / Publish NuGet Package
permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Infrastructure/Infrastructure.csproj

      - name: Build
        run: dotnet build Infrastructure/Infrastructure.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack Infrastructure/Infrastructure.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate
